[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "rolldown"
version = "0.0.1"

[[example]]
bench = false
name = "build"
path = "examples/build.rs"
test = false

[dependencies.swc_common]
features = ["tty-emitter", "concurrent"]
version = "0.14.7"

[dependencies]
ahash = "0.7"
anyhow = "1"
env_logger = "0.9"
log = "0.4"
napi = "1"
napi-derive = "1"
once_cell = "1"
path-absolutize = "3"
rayon = "1.5.1"
swc_ecma_ast = "0.58.1"
swc_ecma_codegen = "0.80.0"
swc_ecma_parser = "0.78.10"
swc_ecma_visit = "0.44"
thiserror = "1"
nodejs_path = "0.0.2"
petgraph = "0.6.0"
swc_atoms = "0.2.9"
disjoint-sets = "0.4.2"