[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "rolldown"
version = "0.0.1"

[[example]]
bench = false
name = "bundle"
path = "examples/bundle.rs"
test = false

[dependencies.swc_common]
features = ["tty-emitter", "concurrent"]
version = "0.14"

[dependencies]
ahash = "0.7"
anyhow = "1"
log = "0.4"
napi = "1"
napi-derive = "1"
once_cell = "1"
path-absolutize = "3"
rayon = "1"
swc_ecma_ast = "0.56"
swc_ecma_codegen = "0.78"
swc_ecma_parser = "0.76"
swc_ecma_visit = "0.42"
thiserror = "1"
