[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "rolldown"
version = "0.0.1"

[[bin]]
bench = false
name = "bundle-lodash-es"
path = "bin/lodash.rs"
test = false

[[bin]]
bench = false
name = "bundle-three-js"
path = "bin/three.rs"
test = false

[dependencies.swc_common]
features = ["tty-emitter", "concurrent"]
version = "0.13.2"
# path = "../../../swc/common"

[dependencies]
ahash = "0.7"
anyhow = "1"
napi = "1"
napi-derive = "1"
once_cell = "1"
path-absolutize = "3"
rayon = "1"
swc_ecma_ast = "0.54"
swc_ecma_codegen = "0.74"
swc_ecma_parser = "0.73"
swc_ecma_visit = "0.40"
# swc_ecma_ast = {path = "../../../swc/ecmascript/ast"}
# swc_ecma_codegen = {path = "../../../swc/ecmascript/codegen"}
# swc_ecma_parser = {path = "../../../swc/ecmascript/parser"}
# swc_ecma_visit = {path = "../../../swc/ecmascript/visit"}
thiserror = "1"
log = "0.4.14"