[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "rolldown"
version = "0.0.1"

[dependencies.swc_common]
features = ["tty-emitter", "concurrent"]
version = "0.13.0"

[dependencies]
ahash = "0.7"
anyhow = "1"
napi = "1"
napi-derive = "1"
once_cell = "1"
path-absolutize = "3"
rayon = "1"
swc_ecma_ast = "0.53"
swc_ecma_codegen = "0.72"
swc_ecma_parser = "0.72"
swc_ecma_visit = "0.39"
thiserror = "1"
