[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "rolldown"
version = "0.0.1"

[dependencies.swc_common]
features = ["tty-emitter", "concurrent"]
version = "0.12.1"

[dependencies]
anyhow = "1"
napi = "1"
napi-derive = "1"
once_cell = "1"
path-absolutize = "3"
swc_ecma_ast = "0.52"
swc_ecma_codegen = "0.70"
swc_ecma_parser = "0.70"
swc_ecma_visit = "0.38"
thiserror = "1"
