name: Benchmark
on:
  push:
    branches:
      - master
      - next-rolldown

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Configure cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo bench --no-run

      - name: Run benchmark
        run: cargo bench | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
      